_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 80
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 80
                - 103
            "3":
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
